# Generated by Django 5.0.4 on 2024-11-30 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentdashboard', '0006_studentsignin_image_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentsignin',
            old_name='parentname_model',
            new_name='Fname_model',
        ),
        migrations.AddField(
            model_name='studentsignin',
            name='DateOfBirth_model',
            field=models.CharField(default='xyz', max_length=60),
        ),
        migrations.AddField(
            model_name='studentsignin',
            name='Mname_model',
            field=models.CharField(default='abc', max_length=60),
        ),
        migrations.AddField(
            model_name='studentsignin',
            name='class10_model',
            field=models.CharField(default='0', max_length=60),
        ),
        migrations.AddField(
            model_name='studentsignin',
            name='class12_model',
            field=models.CharField(default='0', max_length=60),
        ),
        migrations.AddField(
            model_name='studentsignin',
            name='desc_model',
            field=models.TextField(default='NULL'),
        ),
        migrations.AlterField(
            model_name='studentsignin',
            name='password_model',
            field=models.CharField(default='1234', max_length=50),
        ),
    ]
